"""fix_market_articles_schema

Revision ID: b8b1a3f6f8e0
Revises: 8dea90388793
Create Date: 2025-07-20 05:57:47.330771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8b1a3f6f8e0'
down_revision: Union[str, None] = '8dea90388793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_articles', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('market_articles', sa.Column('author', sa.String(length=200), nullable=True))
    op.add_column('market_articles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    
    # Handle market_impact column conversion with proper casting
    op.execute("ALTER TABLE market_articles ALTER COLUMN market_impact TYPE FLOAT USING CASE WHEN market_impact ~ '^[0-9]*\.?[0-9]+$' THEN market_impact::FLOAT ELSE 0.5 END")
    
    op.alter_column('market_articles', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.drop_index('ix_market_articles_content_hash', table_name='market_articles')
    op.drop_index('ix_market_articles_url', table_name='market_articles')
    op.drop_column('market_articles', 'freshness_score')
    op.drop_column('market_articles', 'processing_version')
    op.drop_column('market_articles', 'content_quality_score')
    op.alter_column('market_indicators', 'indicator_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('market_indicators', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('market_indicators', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('market_indicators', 'data_source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('market_sentiment', sa.Column('agent_sentiment_score', sa.Float(), nullable=True))
    op.add_column('market_sentiment', sa.Column('agent_sentiment_label', sa.String(length=50), nullable=True))
    op.add_column('market_sentiment', sa.Column('agent_confidence', sa.Float(), nullable=True))
    op.add_column('market_sentiment', sa.Column('agent_key_insights', sa.JSON(), nullable=True))
    op.add_column('market_sentiment', sa.Column('agent_historical_context', sa.Text(), nullable=True))
    op.add_column('market_sentiment', sa.Column('agent_risk_factors', sa.JSON(), nullable=True))
    op.add_column('market_sentiment', sa.Column('agent_trend_direction', sa.String(length=20), nullable=True))
    op.add_column('market_sentiment', sa.Column('agent_volatility_assessment', sa.String(length=20), nullable=True))
    op.add_column('market_sentiment', sa.Column('agent_next_update', sa.DateTime(), nullable=True))
    op.add_column('market_sentiment', sa.Column('agent_last_updated', sa.DateTime(), nullable=True))
    op.add_column('market_sentiment', sa.Column('has_agent_analysis', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_market_sentiment_has_agent_analysis'), 'market_sentiment', ['has_agent_analysis'], unique=False)
    op.add_column('recommendations', sa.Column('confidence', sa.Float(), nullable=False))
    op.add_column('recommendations', sa.Column('target_price', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('stop_loss', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('overall_score', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('time_horizon', sa.String(length=20), nullable=True))
    op.add_column('recommendations', sa.Column('support_level', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('resistance_level', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('expected_return', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('max_downside', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('recommendations', sa.Column('model_version', sa.String(length=50), nullable=True))
    op.alter_column('recommendations', 'reasoning',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('recommendations', 'created_at')
    op.drop_column('recommendations', 'is_active')
    op.drop_column('recommendations', 'confidence_score')
    op.drop_column('recommendations', 'sell_range_high')
    op.drop_column('recommendations', 'buy_range_low')
    op.drop_column('recommendations', 'volatility_score')
    op.drop_column('recommendations', 'buy_range_high')
    op.drop_column('recommendations', 'sell_range_low')
    op.drop_column('recommendations', 'recommendation_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('recommendation_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('recommendations', sa.Column('sell_range_low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('recommendations', sa.Column('buy_range_high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('recommendations', sa.Column('volatility_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('recommendations', sa.Column('buy_range_low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('recommendations', sa.Column('sell_range_high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('recommendations', sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('recommendations', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('recommendations', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('recommendations', 'reasoning',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('recommendations', 'model_version')
    op.drop_column('recommendations', 'generated_at')
    op.drop_column('recommendations', 'max_downside')
    op.drop_column('recommendations', 'expected_return')
    op.drop_column('recommendations', 'resistance_level')
    op.drop_column('recommendations', 'support_level')
    op.drop_column('recommendations', 'time_horizon')
    op.drop_column('recommendations', 'overall_score')
    op.drop_column('recommendations', 'stop_loss')
    op.drop_column('recommendations', 'target_price')
    op.drop_column('recommendations', 'confidence')
    op.drop_index(op.f('ix_market_sentiment_has_agent_analysis'), table_name='market_sentiment')
    op.drop_column('market_sentiment', 'has_agent_analysis')
    op.drop_column('market_sentiment', 'agent_last_updated')
    op.drop_column('market_sentiment', 'agent_next_update')
    op.drop_column('market_sentiment', 'agent_volatility_assessment')
    op.drop_column('market_sentiment', 'agent_trend_direction')
    op.drop_column('market_sentiment', 'agent_risk_factors')
    op.drop_column('market_sentiment', 'agent_historical_context')
    op.drop_column('market_sentiment', 'agent_key_insights')
    op.drop_column('market_sentiment', 'agent_confidence')
    op.drop_column('market_sentiment', 'agent_sentiment_label')
    op.drop_column('market_sentiment', 'agent_sentiment_score')
    op.alter_column('market_indicators', 'data_source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('market_indicators', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('market_indicators', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('market_indicators', 'indicator_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('market_articles', sa.Column('content_quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('market_articles', sa.Column('processing_version', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('market_articles', sa.Column('freshness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index('ix_market_articles_url', 'market_articles', ['url'], unique=False)
    op.create_index('ix_market_articles_content_hash', 'market_articles', ['content_hash'], unique=False)
    op.alter_column('market_articles', 'content_hash',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('market_articles', 'market_impact',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('market_articles', 'created_at')
    op.drop_column('market_articles', 'author')
    op.drop_column('market_articles', 'content')
    # ### end Alembic commands ###
